version: '3.8'

services:
  php:
    build: 
        context: .
        dockerfile: Dockerfile
    environment:
      MYSQL_DBHOST: "localhost"
      MYSQL_DBUSER: "root"
      MYSQL_DBPASS: "123"
      MYSQL_DBNAME: "food-order"
    ports:
      - 3000:3000

    
      
  db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "123"
            MYSQL_DBNAME: "food-order"
            MYSQL_DBPASS: "123"
            MYSQL_DBHOST: "localhost"
            MYSQL_DBUSER: "admin"
  adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
volumes: 
    sqlData: