version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./php-apache2
            dockerfile: Dockerfile
        depends_on:
          - db
        volumes:
            - ./sources/:/var/www/html/
        environment:
              - ALLOW_OVERRIDE=true
        ports:
            - 8000:80
        links:
            - db

            
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "123"
            MYSQL_DATABASE: food-order
            MYSQL_USER: admin
            MYSQL_PASSWORD: uit
        ports:
            - "9906:3306"
        volumes: 
            - ./sources/food-order.sql:/docker-entrypoint-initdb.d/dump.sql

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080


